package cocktail.core.css.parsers;

/**
 * ...
 * @author Yannick DOMINGUEZ
 */

 enum SelectorParserState {
	IGNORE_SPACES;
	BEGIN_SIMPLE_SELECTOR;
	END_SIMPLE_SELECTOR;
	SIMPLE_SELECTOR;
	END_TYPE_SELECTOR;
	END_CLASS_SELECTOR;
	END_ID_SELECTOR;
	BEGIN_COMBINATOR;
	COMBINATOR;
	BEGIN_PSEUDO_SELECTOR;
	END_UNIVERSAL_SELECTOR;
	PSEUDO_ELEMENT_SELECTOR;
	BEGIN_ATTRIBUTE_SELECTOR;
	INVALID_SELECTOR;
}

enum StyleDeclarationParserState {
	STYLE_NAME;
	STYLE_VALUE;
	IGNORE_SPACES;
	INVALID_STYLE;
	STYLE_SEPARATOR;
	BEGIN;
}

enum StyleValueParserState {
	IGNORE_SPACES;
	BEGIN_VALUE;
	IDENT_FUNCTION;
	NUMBER_INTEGER_DIMENSION_PERCENTAGE;
	SPACE_OR_END;
	INVALID_STYLE_VALUE;
	IMPORTANT;
	END;
	HEX;
	STRING;
}

enum AttributeSelectorParserState {
	ATTRIBUTE;
	OPERATOR;
	BEGIN_VALUE;
	VALUE;
	END_SELECTOR;
	INVALID_SELECTOR;
}

enum StyleRuleParserState {
	IGNORE_SPACES;
	BEGIN_SELECTOR;
	END_SELECTOR;
	SELECTOR;
	BEGIN_STYLES;
	STYLES;
	END_STYLES;
}

enum StyleSheetRulesParserState {
	IGNORE_SPACES;
	BEGIN_RULE;
	RULE;
	END_RULE;
}

enum StyleSheetRuleParserState {
	IGNORE_SPACES;
	BEGIN_RULE;
	BEGIN_AT_RULE;
	END_MEDIA_RULE;
	RULE;
	END_STYLE_RULE;
}